{{- if and .Values.token (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchestr8-collector.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orchestr8-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.token | quote }}
{{- end }}
