{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestr8-collector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orchestr8-collector.labels" . | nindent 4 }}
{{- end }}
